STRIPE_PUBLISHABLE_KEY: “pk_test_2IoYxxa12dmybJzJmS82XO3d”
STRIPE_SECRET_KEY: “sk_test_Inx0VjwqQuJZeANA3ofDptb5"
development:
STRIPE_PUBLISHABLE_KEY: “pk_test_2IoYxxa12dmybJzJmS82XO3d”
STRIPE_SECRET_KEY: “sk_test_Inx0VjwqQuJZeANA3ofDptb5"


GH_BASIC_CLIENT_ID: ‘b384fe66316c40301bf4’
GH_BASIC_SECRET_ID: ‘de5a705c007574075a985f066faff7c319873ee8’
G_MAPS_KEY: “AIzaSyAHiCQpNGfjmAXyIqj0MuxRcVgRQNJIy1o”
G_GEOCODING_KEY: “AIzaSyBsUFQssUqPXoq8Iv_7ZxHssV6FwWtXJ7s”